name: Mystica
version: '${project.version}'
main: me.angeloo.mystica.Mystica
depend:
  - Parties
  - ProtocolLib
api-version: '1.19'
commands:
  Trash:
    description: allows players to throw away items
    usage: /Trash
  Bag:
    description: opens the players bag
    usage: /Bag
  Equipment:
    description: opens equipment
    usage: /Equipment
  ClassSelect:
    description: opens class select
    usage: /ClassSelect
  SeeRawDamage:
    description: allows for better testing of seeing damage
    usage: /SeeRawDamage
  WhatAreMyStats:
    description: allows for players to see their attributes
    usage: /WhatAreMyStats
  MysticaDamage:
    description: allows mms to damage player using this plugin
    usage: /MysticaDamage <target> <caster> <type> <amount>
    permission: developer
  MysticaEffect:
    description: allows mms to inflict status using this plugin
    usage: /MysticaEffect <target> <caster> <type> <modifier>
    permission: developer
  StartFuryTimer:
    description: allows mms to start their fury timer
    usage: /StartFuryTimer <caster> <duration>
    permission: developer
  SkillTargetValidCheck:
    description: allows mms to check validity of their target
    usage: /SkillTargetValidCheck <caster> <target>
    permission: developer
  SkillHitValidCheck:
    description: allows mms to check validity of the player they hit
    usage: /SkillHitValidCheck <caster> <target>
    permission: developer
  ToggleGlobalPvp:
    description: toggles global pvp
    usage: /ToggleGlobalPvp
    permission: developer
  Reforge:
    description: allows testing of reforge mechanic
    usage: /Reforge
    permission: developer
  Upgrade:
    description: allows testing of upgrade mechanic
    usage: /Upgrade
    permission: developer
  Generate:
    description: allows testing of generate mechanic
    usage: /Generate
    permission: developer
  Identify:
    description: allows testing of identify mechanic
    usage: /Identify
    permission: developer
  ManualSave:
    description: saves profiles manually
    usage: /ManualSave
    permission: developer
  DeleteProfile:
    description: deletes a profile
    usage: /DeleteProfile
    permission: developer

permissions:
  developer:
    description: commands for developer stuff
    default: op

