name: Mystica
version: '${project.version}'
main: me.angeloo.mystica.Mystica
depend:
  - Parties
  - ProtocolLib
  - PlaceholderAPI
softdepend:
  - MythicMobs
  - Interactions
api-version: '1.19'
commands:
  Trash:
    description: allows players to throw away items
    usage: /Trash
  ToggleBoardType:
    description: allows players to toggle which board they see
    usage: /ToggleBoardType
  Bag:
    description: opens the players bag
    usage: /Bag
  Equipment:
    description: opens equipment
    usage: /Equipment
  ClassSelect:
    description: opens class select
    usage: /ClassSelect <player>
    permission: developer
  GearSwap:
    description: opens gear swap
    usage: /GearSwap <player>
    permission: developer
  SeeRawDamage:
    description: allows for better testing of seeing damage
    usage: /SeeRawDamage
  WhatAreMyStats:
    description: allows for players to see their attributes
    usage: /WhatAreMyStats
  MysticaDamage:
    description: allows mms to damage player using this plugin
    usage: /MysticaDamage <target> <caster> <type> <amount>
    permission: developer
  MysticaEffect:
    description: allows mms to inflict status using this plugin
    usage: /MysticaEffect <target> <caster> <type> <modifier>
    permission: developer
  ToggleImmunity:
    description: allows devs to not take damage on boss testing
    usage: /ToggleImmunity
    permission: developer
  StartFuryTimer:
    description: allows mms to start their fury timer
    usage: /StartFuryTimer <caster> <duration>
    permission: developer
  ToggleGlobalPvp:
    description: toggles global pvp
    usage: /ToggleGlobalPvp
    permission: developer
  SetMilestone:
    description: lets the game set milestones for players
    usage: /SetMilestone <Player> <Milestone> <true/false>
    permission: developer
  Reforge:
    description: allows testing of reforge mechanic
    usage: /Reforge
    permission: developer
  Upgrade:
    description: allows testing of upgrade mechanic
    usage: /Upgrade
    permission: developer
  Generate:
    description: allows testing of generate mechanic
    usage: /Generate
    permission: developer
  Identify:
    description: allows testing of identify mechanic
    usage: /Identify
    permission: developer
  ManualSave:
    description: saves profiles manually
    usage: /ManualSave
    permission: developer
  ForcePortals:
    description: forces demon portals to spawn
    usage: /ForcePortals
    permission: developer
  SavePaths:
    description: saves paths manually
    usage: /SavePaths
    permission: developer
  DeleteProfile:
    description: deletes a profile
    usage: /DeleteProfile
    permission: developer
  MysticaInteractions:
    description: allows mms to check for mystica data before determining which interaction to start
    usage: /MysticaInteractions <Interaction> <Player>
    permission: developer
  PathTool:
    description: gives player the path tool
    usage: /PathTool
    permission: developer
  DisplayPath:
    description: lets server display a path for the player
    usage: /DisplayPath <Player> <x> <y> <z>
    permission: developer
  Cosmetic:
    description: lets dev test cosmetics
    usage: /Cosmetic
    permission: developer
  BossLevel:
    description: lets mms open boss level inv
    usage: /BossLevel
    permission: developer
  GiveSoulStone:
    description: lets devs give soulstones
    usage: /GiveSoulStone <player> <amount>
    permission: developer
  MysticaQuest:
    description: opens quest books
    usage: /MysticaQuest <player> <quest/accept>
  HitValidCheck:
    description: lets mms see if what they hit with a skill is valid
    usage: /HitValidCheck <caster> <target>
    permission: developer
  SetCaution:
    description: lets mms mess with fake player ai
    usage: /SetCaution <entityuuid> <boolean>
    permission: developer
  SignalNearbyNpc:
    description: lets interactions signal mms
    usage: /SignalNearbyNpc <player> <signal>
    permission: developer
  StopCompanionRotation:
    description: lets companions stop their rotation
    usage: /StopCompanionRotation <target.uuid>
    permission: developer
  DisplayInterruptBar:
    description: lets mm display their interrupt bar
    usage: /DisplayInterruptBar <caster.uuid> <speed> <max>
    permission: developer

permissions:
  developer:
    description: commands for developer stuff
    default: op

